config/routes.rb
Rails.application.routes.draw do
    resources :reports, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :template, presence: true
  validates :sensor_name, presence: true
  validates :sensor_type, presence: true
  validates :sensor_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/).first
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def index
      @reports = Report.all
    end

    def show
      @report = Report.find(params[:id])
      respond_to do |format|
        format.html
        format.json
        format.pdf { render template: 'reports/report', pdf: 'Report', layout: 'pdf.html'}
      end
    end

    def new
      @report = Report.new
    end

    def create
      @report = Report.new(report_params)

      if @report.save
        redirect_to reports_path, notice: t('.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @report = Report.find(params[:id])
    end

    def update
      @report = Report.find(params[:id])

      if @report.update(report_params)
        redirect_to reports_path, notice: t('.updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @report = Report.find(params[:id])
      @report.destroy

      redirect_to reports_path, notice: t('.destroyed'), status: :see_other
    end
    
    private

    def report_params
      params.require(:report).permit(:title, :description, :template, :sensor_name, :sensor_type, :sensor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_time(time, options = {})
    # Set the format
    format = options[:year].nil? ? '%Y/%m/%d at' : '%m/%d at'
    format = if options[:bold]
               "#{format} <strong>%H:%M</strong>"
             else
               "#{format} %H:%M"
             end
    format = "#{format} %:z" if options[:timezone]

    if time.nil? || time.blank?
      # Set the undefined string
      undefined_string = options[:undefinedString] ||
                         Time.zone.now.strftime(format)
      undefined_string.html_safe
    else
      time.strftime(format).html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redboder Reports | Informes Avanzados</title>
    <%= csrf_meta_tags %>

    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'shared/flash' %>
    <div class="main">
      <%= render 'shared/header' %>
      <%= yield %>
    </div>
    <div>
      <p><%= Date.today %></p>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redboder Report pdf</title>
    <meta charset="utf-8">
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  </head>

  <body>
     <%= yield %>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_for @report do |form| %>
  <% @report.errors.full_messages.each do |error| %>
  <div id='errors'>
    <%= error %>
  </div>
  <% end %>

  <div class="row">
    <div class="col-25">
      <%= form.label :title %>
    </div>
    <div class="col-25">
      <%= form.text_field :title %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-25">
      <%= form.label :description %>
    </div>
    <div class="col-75">
      <%= form.text_area :description %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-25">
      <%= form.label :template%>
    </div>
    <div class="col-75">
      <%= form.text_area :template %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-25">
      <%= form.label :sensor_type %>
    </div>
    <div class="col-25">
      <%= form.label :sensor_name %>
    </div>
    <div class="col-25">
      <%= form.label :sensor_id %>
    </div>
  </div>
  <div>
    <div class="col-25">
      <%= form.text_field :sensor_type %>
    </div>
    <div class="col-25">
      <%= form.number_field :sensor_id %>
    </div>
    <div class="col-25">
      <%= form.text_field :sensor_name %>
    </div>      
  </div>

  <div class="row">
    <div class="col-25">
      <%= form.submit %>
    </div>  
  </div>
  <% end %>

app/views/reports/edit.html.erb
<h2><%= t('.title') %></h2>
<%= render 'form' %>

app/views/reports/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1 class="panel-title"><%= t('.title') %></h1>
  </div>

  <div class="panel-body">
  <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Last Modified</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            <% @reports.each do |report| %>
              <tr>
                <td> 
                  <%= link_to report_path(report), class: 'report' do%>
                    <p><%=report.title%></p>
                  <% end %>
                </td>
                <td>
                  <p><%=report.description%></p>
                </td>
                <td>
                <p><%=format_time report.updated_at, {undefinedString: "Never"}%></p>
                </td>
                <td class="last row-right">
                   <%= link_to content_tag(:i, nil, class: 'icon-fixed-width icon-pencil'), edit_report_path(report), class: 'btn' %>
                   <%= link_to content_tag(:i, nil, class: 'icon-fixed-width icon-trash'), report_path(report), method: :delete, data: { confirm: t('common.confirm') }, class: 'btn' %>
              </tr>
             <% end %>
            </tbody>
          </table>
   
  </div>

</div>

app/views/reports/new.html.erb
<h2><%= t('.title') %></h2>
<%= render 'form' %>

app/views/reports/report.pdf.erb
<p><%= @report.title%></p> 

<div class='template' id="wysiwyg">
    <p><%= @report.template%></p>
 </div>

app/views/reports/show.html.erb
<h1 class='title'><%= @report.title %></h1>
<p class='description'><%= @report.description %></p>
 <div class='template' id="wysiwyg">
     <p><%= @report.template%></p> 
 </div>
 <div id="sensorData">
     <p><small> <%= @report.sensor_id%> <%= @report.sensor_name%> de tipo:"<%= @report.sensor_type%> " </small></p> 
</div>

<%= link_to t('.pdf'), report_path(@report) + '.pdf', :target =>'_blank' %> |
<%= link_to t('.edit'), edit_report_path(@report) %> |
<%= link_to t('.delete'), report_path(@report), method: :delete, data: { confirm: t('common.confirm') } %>

app/views/shared/_flash.html.erb
<%= alert %>
<%= notice %>

app/views/shared/_header.html.erb
<nav class="navbar">
  <div class="navbar-header">
      <%= link_to reports_path do %>
        <span class="navbar-brand"> Redborder Reports </span>
      <% end %>
  </div>
  <div class="navbar-collapse">
    <ul class="nav navbar-right navbar-nav">
        <li>
          <%= link_to content_tag(:i, t('.add'), class: 'icon-plus'), new_report_path %>
        </li>
    </ul>
  </div>
</nav>


  